#!/usr/bin/bash

cd "$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )" || exit

C_RED='\e[38;5;9m'
C_INVERT='\e[7m'
C_RESET='\e[0m'

BIN_PATH=/usr/bin
FLAG_DIR=/usr/share/oxidizr-arch

## COREUTILS

UU_CORE_PREF=uu
CU_CORE_PREF=cu

uutils-core () {
    echo UU-CORE

    [ ! -f ${BIN_PATH}/${CU_CORE_PREF}-ls ] && echo -e "${C_RED}ERROR: Not set up${C_RESET}" >&2 && exit 1

    cat ${FLAG_DIR}/lists/cu-core-files-move | xargs -I@ uu-cp -p ${BIN_PATH}/${UU_CORE_PREF}-@ ${BIN_PATH}/@

    touch ${FLAG_DIR}/core-on
}

coreutils-core () {
    echo CU-CORE

    [ ! -f ${BIN_PATH}/${CU_CORE_PREF}-ls ] && echo -e "${C_RED}ERROR: Not set up${C_RESET}" >&2 && exit 1

    cat ${FLAG_DIR}/lists/cu-core-files-move | xargs -I@ uu-cp -p ${BIN_PATH}/${CU_CORE_PREF}-@ ${BIN_PATH}/@

    rm ${FLAG_DIR}/core-on
}

setup-core () {
    echo SETUP-CORE

    [ -f ${BIN_PATH}/${CU_CORE_PREF}-ls ] && echo -e "${C_RED}ERROR: Already set up${C_RESET}" >&2 && exit 1
    pacman -Qi uutils-coreutils &> /dev/null || { echo "uutils-coreutils not installed"; exit 0; }

    cat ${FLAG_DIR}/lists/cu-core-files-move | xargs -I@ uu-cp -p ${BIN_PATH}/@ ${BIN_PATH}/${CU_CORE_PREF}-@

    touch ${FLAG_DIR}/core-setup

    [ -f ${FLAG_DIR}/core-on ] && uutils-core

    exit 0
}

remove-core () {
    echo REMOVE-CORE

    [ ! -f ${BIN_PATH}/${CU_CORE_PREF}-ls ] && echo -e "${C_RED}ERROR: Not set up${C_RESET}" >&2 && exit 1

    cat ${FLAG_DIR}/lists/cu-core-files-move | xargs -I@ uu-cp -p ${BIN_PATH}/${CU_CORE_PREF}-@ ${BIN_PATH}/@
    cat ${FLAG_DIR}/lists/cu-core-files-move | xargs -I@ rm ${BIN_PATH}/${CU_CORE_PREF}-@

    rm ${FLAG_DIR}/core-setup
}

pre-transaction-core () {
    [ ! -f ${FLAG_DIR}/core-setup ] && exit
    touch ${FLAG_DIR}/core-setup-UPDATE
    remove-core
}

post-transaction-core () {
    [ ! -f ${FLAG_DIR}/core-setup-UPDATE ] && exit
    rm ${FLAG_DIR}/core-setup-UPDATE
    setup-core
}


## FINDUTILS

UU_FIND_PREF=uu
CU_FIND_PREF=cu

uutils-find () {
    echo UU-FIND

    [ ! -f ${BIN_PATH}/${CU_FIND_PREF}-find ] && echo -e "${C_RED}ERROR: Not set up${C_RESET}" >&2 && exit 1

    cat ${FLAG_DIR}/lists/cu-find-files-move | uu-xargs -I@ cp -p ${BIN_PATH}/${UU_FIND_PREF}-@ ${BIN_PATH}/@

    touch ${FLAG_DIR}/find-on
}

coreutils-find () {
    echo CU-FIND

    [ ! -f ${BIN_PATH}/${CU_FIND_PREF}-find ] && echo -e "${C_RED}ERROR: Not set up${C_RESET}" >&2 && exit 1

    cat ${FLAG_DIR}/lists/cu-find-files-move | uu-xargs -I@ cp -p ${BIN_PATH}/${CU_FIND_PREF}-@ ${BIN_PATH}/@

    rm ${FLAG_DIR}/find-on
}

setup-find () {
    echo SETUP-FIND

    [ -f ${BIN_PATH}/${CU_FIND_PREF}-find ] && echo -e "${C_RED}ERROR: Already set up${C_RESET}" >&2 && exit 1
    pacman -Qi uutils-coreutils &> /dev/null || { echo "uutils-findutils not installed"; exit 0; }

    cat ${FLAG_DIR}/lists/cu-find-files-move | uu-xargs -I@ cp -p ${BIN_PATH}/@ ${BIN_PATH}/${CU_FIND_PREF}-@

    touch ${FLAG_DIR}/find-setup

    [ -f ${FLAG_DIR}/find-on ] && uutils-find

    exit 0
}

remove-find () {
    echo REMOVE-FIND

    [ ! -f ${BIN_PATH}/${CU_FIND_PREF}-find ] && echo -e "${C_RED}ERROR: Not set up${C_RESET}" >&2 && exit 1

    cat ${FLAG_DIR}/lists/cu-find-files-move | uu-xargs -I@ cp -p ${BIN_PATH}/${CU_FIND_PREF}-@ ${BIN_PATH}/@
    cat ${FLAG_DIR}/lists/cu-find-files-move | uu-xargs -I@ rm ${BIN_PATH}/${CU_FIND_PREF}-@

    rm ${FLAG_DIR}/find-setup
}

pre-transaction-find () {
    [ ! -f ${FLAG_DIR}/find-setup ] && exit
    touch ${FLAG_DIR}/find-setup-UPDATE
    remove-find
}

post-transaction-find () {
    [ ! -f ${FLAG_DIR}/find-setup-UPDATE ] && exit
    rm ${FLAG_DIR}/find-setup-UPDATE
    setup-find
}


## SUDO

RS_SUDO_SUF=rs
VN_SUDO_SUF=vn

rust-sudo () {
    echo RUST-SUDO

    [ ! -f ${BIN_PATH}/su-${VN_SUDO_SUF} ] && echo -e "${C_RED}ERROR: Not set up${C_RESET}" >&2 && exit 1

    cp -p ${BIN_PATH}/su-${RS_SUDO_SUF} ${BIN_PATH}/su || exit 1
    cp -p ${BIN_PATH}/sudo-${RS_SUDO_SUF} ${BIN_PATH}/sudo || exit 1
    cp -p ${BIN_PATH}/visudo-${RS_SUDO_SUF} ${BIN_PATH}/visudo || exit 1

    touch ${FLAG_DIR}/sudo-on
}

vanilla-sudo () {
    echo VANILLA-SUDO

    [ ! -f ${BIN_PATH}/su-${VN_SUDO_SUF} ] && echo -e "${C_RED}ERROR: Not set up${C_RESET}" >&2 && exit 1

    cp -p ${BIN_PATH}/su-${VN_SUDO_SUF} ${BIN_PATH}/su || exit 1
    cp -p ${BIN_PATH}/sudo-${VN_SUDO_SUF} ${BIN_PATH}/sudo || exit 1
    cp -p ${BIN_PATH}/visudo-${VN_SUDO_SUF} ${BIN_PATH}/visudo || exit 1

    rm ${FLAG_DIR}/sudo-on

    exit 0
}

setup-sudo () {
    echo SETUP-SUDO

    [ -f ${BIN_PATH}/su-${VN_SUDO_SUF} ] && echo -e "${C_RED}ERROR: Already set up${C_RESET}" >&2 && exit 1
    pacman -Qi sudo-rs &> /dev/null || { echo "sudo-rs not installed"; exit 0; }

    cp -p ${BIN_PATH}/su ${BIN_PATH}/su-${VN_SUDO_SUF} || exit 1
    cp -p ${BIN_PATH}/sudo ${BIN_PATH}/sudo-${VN_SUDO_SUF} || exit 1
    cp -p ${BIN_PATH}/visudo ${BIN_PATH}/visudo-${VN_SUDO_SUF} || exit 1

    touch ${FLAG_DIR}/sudo-setup

    [ -f ${FLAG_DIR}/sudo-on ] && rust-sudo

    exit 0
}

remove-sudo () {
    echo REMOVE-SUDO

    [ ! -f ${BIN_PATH}/su-${VN_SUDO_SUF} ] && echo -e "${C_RED}ERROR: Not set up${C_RESET}" >&2 && exit 1

    cp -p ${BIN_PATH}/su-${VN_SUDO_SUF} ${BIN_PATH}/su || exit 1
    cp -p ${BIN_PATH}/sudo-${VN_SUDO_SUF} ${BIN_PATH}/sudo || exit 1
    cp -p ${BIN_PATH}/visudo-${VN_SUDO_SUF} ${BIN_PATH}/visudo || exit 1

    rm ${BIN_PATH}/su-${VN_SUDO_SUF} || exit 1
    rm ${BIN_PATH}/sudo-${VN_SUDO_SUF} || exit 1
    rm ${BIN_PATH}/visudo-${VN_SUDO_SUF} || exit 1

    rm ${FLAG_DIR}/sudo-setup
}

pre-transaction-sudo () {
    [ ! -f ${FLAG_DIR}/sudo-setup ] && exit
}

post-transaction-sudo () {
    [ ! -f ${FLAG_DIR}/sudo-setup ] && exit

    cp -p ${BIN_PATH}/su ${BIN_PATH}/su-${VN_SUDO_SUF} || exit 1
    cp -p ${BIN_PATH}/sudo ${BIN_PATH}/sudo-${VN_SUDO_SUF} || exit 1
    cp -p ${BIN_PATH}/visudo ${BIN_PATH}/visudo-${VN_SUDO_SUF} || exit 1

    [ ! -f ${FLAG_DIR}/sudo-on ] && exit

    rust-sudo
}


## LAUNCH

#echo -e "${C_RED}${C_INVERT} WARNING!!! ${C_RESET}${C_RED} This is an extremely dangerous script, since it manipulates core utilities and sudo"
#echo -e "             Don't run this without examining AND FULLY UNDERSTANDING it's contents, unless you want your OS bricked${C_RESET}"
#echo

[ -z "$1" ] && echo "No arguments" >&2 && exit 0
if declare -f "$1" > /dev/null
then
    [ "$(/usr/bin/id -u)" -ne 0 ] && echo -e "${C_RED}ERROR: You cannot run this unless you are root${C_RESET}" >&2 && exit 1
    "$@"
else
    echo "'$1' is not a known function name" >&2
    exit 1
fi
